### ISSUE TITLE
After deleting SmoothBrain Note Type, all cards are being added as Basic

### ISSUE THREAD

**Issue by alexbowe** [alexbowe/smoothbrain#31]

**Comment by abdnh** [comment]
Maybe it's caused by [this](https://github.com/smoothbrain-ai/smoothbrain-anki/pull/14/commits/df8dbc90606f737c16467d9b73c1825a0ff31cc6) (though I'd expect the SmoothBrain notetype not to be used at all in this case)? It was added back by your merge commit (probably by accident).
